spring:
  application:
    name: campus-checkin
  profiles:
    active: dev
  main:
    allow-circular-references: true
  # 定义Jackson序列化日期格式
  Jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    # 禁止 Jackson 把时间序列化成时间戳, 改为字符串时间格式
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: ${sky.datasource.driver-class-name}
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
  data:
    redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
      database: ${sky.redis.database}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    # 开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# MyBatis 内部本来就会输出日志
# 但是默认日志级别是 DEBUG
# 如果你的日志系统（Spring Boot 默认 Logback）级别是 INFO，就不会显示
# 当你配置：
# logging.level.com.wangwei.mapper=debug
# 相当于告诉日志框架：
#Mapper包下的日志允许输出 DEBUG
#logging:
#  level:
#    com.wangwei.mapper: DEBUG
campus:
  jwt:
    secret-key: seniorL-super-secret-key-for-jwt-authentication-2026
    # 86400000 = 24小时
    ttl: 86400000
    token-name: Authorization
